### ISSUE TITLE
Make it easier to share/enhance blockdiag diagrams

### ISSUE THREAD

**Issue by techtonik** [yakshaveinc/tasks#5]
Blockdiag is a [tool](http://interactive.blockdiag.com/) for creating diagrams, and it only allows to save SVG. GitHub and other sites have troubles with rendering SVG images, so it should be specially formatted for GitHub markup, but a more convenient way is to add an option to render as PNG.

https://bitbucket.org/blockdiag/blockdiag_interactive_shell/issues/4/save-as-png

**Comment by techtonik** [comment]
See https://github.com/badges/shields/issues/507 for example of embedding and optimizing SVG for GitHub.

Looks like Firefox 57.0 has troubles rendering that, or maybe something changed on GitHub side. Badges below should display logo at the left:

![screenshot-2017-11-24 logos cleanup and appveyor by techtonik pull request 812 badges shields](https://user-images.githubusercontent.com/515889/33205654-c4cae544-d118-11e7-81d3-e0a201d6d6b5.png)

**Comment by techtonik** [comment]
Here is how to draw data URL to canvas: https://stackoverflow.com/questions/4773966/drawing-an-image-from-a-data-url-to-a-canvas

Note that if width/height is not set on `<svg>`element, then Firefox 57.0 renders canvas empty - see http://phrogz.net/SVG/svg_to_png.xhtml

![image](https://user-images.githubusercontent.com/515889/33206145-60b34d06-d11a-11e7-8a85-4e8cdc494ffe.png)

A solution could be to copy `svg` and set them with DOM.

**Comment by abitrolly** [comment]
Another good tool - https://github.com/knsv/mermaid

**Comment by abitrolly** [comment]
Seems like the problems is solved with these tools.

* https://kroki.io/examples.html
* https://mermaid.live/
